local MainAPI = loadstring(game:HttpGet("https://raw.githubusercontent.com/yes1nt/friedpotato/refs/heads/main/API/MAIN%20API.lua"))()
local api = MainAPI:LoadTsbgAPI()
local Main = api:CreateMoveset("Slasher - Void")
api:SetSupportedHeroes({"Deadly Ninja"})
api:Load()
Main:LoadSlasherVoid()
